--------------------------------------------------------
-- Archivo creado  - domingo-octubre-20-2019   
--------------------------------------------------------
--------------------------------------------------------
---Tablespace SMALLFILE
create smallfile tablespace BET_ITM
datafile 'D:\taller\BET_ITM1.dbf' size 512M,
         'D:\taller\BET_ITM2.dbf' size 512M
extent management local autoallocate;

---Tablespace BIGFILE
create bigfile tablespace BET_AUDITING
datafile 'D:\taller\BET_AUDITING1.dbf' size 2G
extent management local autoallocate;

---Tablespace UNDO
create undo tablespace UNDO_BET_ITM
datafile 'D:\taller\UNDO_BET_ITM1.dbf' size 500M;

alter session set "_ORACLE_SCRIPT"=TRUE;

---3.)Perfiles

create profile developer limit
sessions_per_user     1
connect_time          60
idle_time             30
failed_login_attempts 5
password_life_time    90;

create profile web_application limit
sessions_per_user     5
connect_time          unlimited
idle_time             unlimited
failed_login_attempts 2
password_life_time    30;

create profile dba_admin limit
sessions_per_user     1
connect_time          30
idle_time             unlimited
failed_login_attempts 2
password_life_time    30;

create profile analyst limit
sessions_per_user     1
connect_time          30
idle_time             5
failed_login_attempts 3
password_life_time    30
password_grace_time   3;

create profile support_III limit
sessions_per_user     1
connect_time          240
idle_time             5
failed_login_attempts 3
password_life_time    20
password_grace_time   3;

create profile reporter limit
sessions_per_user     1
connect_time          90
idle_time             15
failed_login_attempts 4
password_life_time    unlimited
password_grace_time   5;

create profile auditor limit
sessions_per_user     1
connect_time          90
idle_time             15
failed_login_attempts 4
password_life_time    unlimited
password_grace_time   5;


---5.) Usuarios

create user usuario_1
identified by usuario1
default tablespace BET_ITM
quota unlimited on BET_ITM
profile developer;

create user usuario_2
identified by usuario2
default tablespace BET_ITM
quota unlimited on BET_ITM
profile web_application;

create user usuario_3
identified by usuario3
default tablespace BET_ITM
quota unlimited on BET_ITM
profile dba_admin;

create user usuario_4
identified by usuario4
default tablespace BET_ITM
quota unlimited on BET_ITM
profile analyst;

create user usuario_5
identified by usuario5
default tablespace BET_ITM
quota unlimited on BET_ITM
profile support_III;

create user usuario_6
identified by usuario6
default tablespace BET_ITM
quota unlimited on BET_ITM
profile reporter;

create user usuario_7
identified by usuario7
default tablespace BET_AUDITING
quota unlimited on BET_AUDITING
profile auditor;

create user usuario_8
identified by usuario8
default tablespace BET_ITM
quota unlimited on BET_ITM
profile developer;

create user usuario_9
identified by usuario9
default tablespace BET_ITM
quota unlimited on BET_ITM
profile web_application;

create user usuario_10
identified by usuario10
default tablespace BET_ITM
quota unlimited on BET_ITM
profile dba_admin;

create role INICIO_SESION;

GRANT create session to INICIO_SESION;
GRANT INICIO_SESION to usuario_1;
GRANT INICIO_SESION to usuario_2;
GRANT INICIO_SESION to usuario_3;
GRANT INICIO_SESION to usuario_4;
GRANT INICIO_SESION to usuario_5;
GRANT INICIO_SESION to usuario_6;
GRANT INICIO_SESION to usuario_7;
GRANT INICIO_SESION to usuario_8;
GRANT INICIO_SESION to usuario_9;
GRANT INICIO_SESION to usuario_10;

GRANT CREATE SESSION,
CREATE TABLE,
CREATE VIEW,
CREATE PROCEDURE,
CREATE SEQUENCE,
CREATE TABLESPACE
TO usuario_1;

--------------------------------------------------------
--  DDL for Table APUESTAS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."APUESTAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ESTADO_APUESTA_ID" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE), 
	"USUARIO_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table APUESTAS_PARTIDOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."APUESTAS_PARTIDOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PARTIDO_ID" NUMBER, 
	"APUESTA_ID" NUMBER, 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table AUDITORIAS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."AUDITORIAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FECHA" TIMESTAMP (6), 
	"TABLA" VARCHAR2(100 BYTE), 
	"REGISTRO_ID" VARCHAR2(100 BYTE), 
	"ACCION" VARCHAR2(100 BYTE), 
	"USUARIO" VARCHAR2(100 BYTE), 
	"IP" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table BANCOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."BANCOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table BONOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."BONOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CODIGO_BONO" NUMBER, 
	"FECHA_ACTIVACION" DATE, 
	"FECHA_CADUCIDAD" DATE, 
	"USUARIO_ID" NUMBER, 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table COMPROBANTES
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."COMPROBANTES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"TAMANO_ARCHIVO" VARCHAR2(10 BYTE), 
	"EXTENSION" VARCHAR2(10 BYTE), 
	"URL" VARCHAR2(200 BYTE), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table CUOTAS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."CUOTAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PARTIDO_ID" NUMBER, 
	"TIPO_APUESTA_ID" NUMBER, 
	"VISITANTE" FLOAT(126), 
	"EMPATE" FLOAT(126), 
	"LOCAL" FLOAT(126), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."DEPARTAMENTOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CODIGO_DEPARTAMENTO" NUMBER, 
	"NOMBRE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table DEPOSITOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."DEPOSITOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MEDIO_PAGO_ID" NUMBER, 
	"ESTADO_DEPOSITO_ID" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"VALOR" NUMBER(12,2), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table EQUIPOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."EQUIPOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table ESTADOS_APUESTAS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."ESTADOS_APUESTAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table ESTADOS_DEPOSITOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."ESTADOS_DEPOSITOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table LIMITES_BLOQUEOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."LIMITES_BLOQUEOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USUARIO_ID" NUMBER, 
	"MONTO_APUESTA_ID" NUMBER, 
	"MONTO_PERDIDA_ID" NUMBER, 
	"LIMITE_DEPOSITO_ID" NUMBER, 
	"FECHA_TRANSACCION" TIMESTAMP (6), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table LIMITES_DEPOSITOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."LIMITES_DEPOSITOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"VALOR_DIARIO" NUMBER, 
	"VALOR_SEMANAL" NUMBER, 
	"VALOR_MENSUAL" NUMBER, 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table MEDIOS_PAGOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."MEDIOS_PAGOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"VALOR_MINIMO" NUMBER, 
	"VALOR_MAXIMO" NUMBER, 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table MONTOS_APUESTAS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."MONTOS_APUESTAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"VALOR_DIARIO" NUMBER, 
	"VALOR_SEMANAL" NUMBER, 
	"VALOR_MENSUAL" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table MONTOS_PERDIDAS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."MONTOS_PERDIDAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"VALOR_DIARIO" NUMBER, 
	"VALOR_SEMANAL" NUMBER, 
	"VALOR_MENSUAL" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table MOVIMIENTOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."MOVIMIENTOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USUARIO_ID" NUMBER, 
	"DEPOSITO_ID" NUMBER, 
	"RETIRO_ID" NUMBER, 
	"SALDO" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table MUNICIPIOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."MUNICIPIOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CODIGO_MUNICIPIO" NUMBER, 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"DEPARTAMENTO_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table PARTIDOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."PARTIDOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"VISITANTE" NUMBER, 
	"LOCAL" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"ESTADO" VARCHAR2(15 BYTE), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table PERSONAS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."PERSONAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TITULO" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"SEGUNDO_NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"SEGUNDO_APELLIDO" VARCHAR2(50 BYTE), 
	"CODIGO_BONO" VARCHAR2(50 BYTE), 
	"ZONA_HORARIA" VARCHAR2(30 BYTE), 
	"TIPO_DOCUMENTO" VARCHAR2(4 BYTE), 
	"NUMERO_DOCUMENTO" VARCHAR2(13 BYTE), 
	"LUGAR_EXPEDICION" VARCHAR2(30 BYTE), 
	"FECHA_EXPEDICION" DATE, 
	"LUGAR_NACIMIENTO" VARCHAR2(50 BYTE), 
	"DIRECCION_RESIDENCIA" VARCHAR2(100 BYTE), 
	"SEGUNDA_DIRECCION" VARCHAR2(100 BYTE), 
	"CORREO_ELECTRONICO" VARCHAR2(100 BYTE), 
	"NUMERO_CELULAR" VARCHAR2(11 BYTE), 
	"CODIGO_POSTAL" VARCHAR2(7 BYTE), 
	"DEPARTAMENTO_ID" NUMBER, 
	"MUNICIPIO_ID" NUMBER, 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table PREFERENCIAS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."PREFERENCIAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USUARIO_ID" NUMBER, 
	"ACEPTA_INFORMACION" VARCHAR2(2 BYTE), 
	"IDIOMA_CORREO" VARCHAR2(20 BYTE), 
	"ACEPTA_BOLETIN" VARCHAR2(2 BYTE), 
	"ACEPTA_CORREO_APUESTAS" VARCHAR2(2 BYTE), 
	"ACEPTA_NOTIFICACION" VARCHAR2(2 BYTE), 
	"ACEPTA_AVISO_APUESTAS" VARCHAR2(2 BYTE), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table REQUISITOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."REQUISITOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"RETIRO_ID" NUMBER, 
	"COMPROBANTE_ID" NUMBER, 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table RESULTADOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."RESULTADOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PARTIDO_ID" NUMBER, 
	"VISITANTE" NUMBER, 
	"LOCAL" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"ESTADO" VARCHAR2(15 BYTE), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table RETIROS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."RETIROS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"BANCO_ID" NUMBER, 
	"FECHA_SOLICITUD" TIMESTAMP (6), 
	"FECHA_DESEMBOLSO" TIMESTAMP (6), 
	"VALOR" NUMBER(12,2), 
	"CUMPLE_COMPROBANTES" VARCHAR2(3 BYTE), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE), 
	"NUMERO_CUENTA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table SESIONES
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."SESIONES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USUARIO_ID" NUMBER, 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE, 
	"LIMITE_SESION" NUMBER, 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table TIPOS_APUESTAS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."TIPOS_APUESTAS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "USUARIO_1"."USUARIOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PERSONA_ID" NUMBER, 
	"CEDULA" VARCHAR2(50 BYTE), 
	"CONTRASENA" VARCHAR2(50 BYTE), 
	"ZONA_HORARIA" VARCHAR2(30 BYTE), 
	"ESTADO_REGISTRO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "BET_ITM" ;
REM INSERTING into USUARIO_1.APUESTAS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.APUESTAS_PARTIDOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.AUDITORIAS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.BANCOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.BONOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.COMPROBANTES
SET DEFINE OFF;
REM INSERTING into USUARIO_1.CUOTAS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.DEPARTAMENTOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.DEPOSITOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.EQUIPOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.ESTADOS_APUESTAS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.ESTADOS_DEPOSITOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.LIMITES_BLOQUEOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.LIMITES_DEPOSITOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.MEDIOS_PAGOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.MONTOS_APUESTAS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.MONTOS_PERDIDAS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.MOVIMIENTOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.MUNICIPIOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.PARTIDOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.PERSONAS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.PREFERENCIAS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.REQUISITOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.RESULTADOS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.RETIROS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.SESIONES
SET DEFINE OFF;
REM INSERTING into USUARIO_1.TIPOS_APUESTAS
SET DEFINE OFF;
REM INSERTING into USUARIO_1.USUARIOS
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table AUDITORIAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."AUDITORIAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."AUDITORIAS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."AUDITORIAS" MODIFY ("TABLA" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."AUDITORIAS" MODIFY ("REGISTRO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."AUDITORIAS" MODIFY ("ACCION" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."AUDITORIAS" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."AUDITORIAS" MODIFY ("IP" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."AUDITORIAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MONTOS_APUESTAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."MONTOS_APUESTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MONTOS_APUESTAS" MODIFY ("VALOR_DIARIO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MONTOS_APUESTAS" MODIFY ("VALOR_SEMANAL" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MONTOS_APUESTAS" MODIFY ("VALOR_MENSUAL" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MONTOS_APUESTAS" ADD CHECK (VALOR_DIARIO > 0) ENABLE;
  ALTER TABLE "USUARIO_1"."MONTOS_APUESTAS" ADD CHECK (VALOR_SEMANAL > 0) ENABLE;
  ALTER TABLE "USUARIO_1"."MONTOS_APUESTAS" ADD CHECK (VALOR_MENSUAL > 0) ENABLE;
  ALTER TABLE "USUARIO_1"."MONTOS_APUESTAS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."MONTOS_APUESTAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."USUARIOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."USUARIOS" MODIFY ("PERSONA_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."USUARIOS" MODIFY ("CEDULA" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."USUARIOS" MODIFY ("CONTRASENA" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."USUARIOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."USUARIOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPOS_APUESTAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."TIPOS_APUESTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."TIPOS_APUESTAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."TIPOS_APUESTAS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."TIPOS_APUESTAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table APUESTAS_PARTIDOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."APUESTAS_PARTIDOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."APUESTAS_PARTIDOS" MODIFY ("PARTIDO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."APUESTAS_PARTIDOS" MODIFY ("APUESTA_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."APUESTAS_PARTIDOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."APUESTAS_PARTIDOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."DEPARTAMENTOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."DEPARTAMENTOS" MODIFY ("CODIGO_DEPARTAMENTO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."DEPARTAMENTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."DEPARTAMENTOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MONTOS_PERDIDAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."MONTOS_PERDIDAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MONTOS_PERDIDAS" MODIFY ("VALOR_DIARIO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MONTOS_PERDIDAS" MODIFY ("VALOR_SEMANAL" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MONTOS_PERDIDAS" MODIFY ("VALOR_MENSUAL" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MONTOS_PERDIDAS" ADD CHECK (VALOR_DIARIO > 0) ENABLE;
  ALTER TABLE "USUARIO_1"."MONTOS_PERDIDAS" ADD CHECK (VALOR_SEMANAL > 0) ENABLE;
  ALTER TABLE "USUARIO_1"."MONTOS_PERDIDAS" ADD CHECK (VALOR_MENSUAL > 0) ENABLE;
  ALTER TABLE "USUARIO_1"."MONTOS_PERDIDAS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."MONTOS_PERDIDAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADOS_APUESTAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."ESTADOS_APUESTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."ESTADOS_APUESTAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."ESTADOS_APUESTAS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."ESTADOS_APUESTAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MUNICIPIOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."MUNICIPIOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MUNICIPIOS" MODIFY ("CODIGO_MUNICIPIO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MUNICIPIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MUNICIPIOS" MODIFY ("DEPARTAMENTO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MUNICIPIOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPROBANTES
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."COMPROBANTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."COMPROBANTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."COMPROBANTES" MODIFY ("TAMANO_ARCHIVO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."COMPROBANTES" MODIFY ("EXTENSION" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."COMPROBANTES" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."COMPROBANTES" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."COMPROBANTES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIMITES_DEPOSITOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."LIMITES_DEPOSITOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."LIMITES_DEPOSITOS" MODIFY ("VALOR_DIARIO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."LIMITES_DEPOSITOS" MODIFY ("VALOR_SEMANAL" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."LIMITES_DEPOSITOS" MODIFY ("VALOR_MENSUAL" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."LIMITES_DEPOSITOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."LIMITES_DEPOSITOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESULTADOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."RESULTADOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."RESULTADOS" MODIFY ("PARTIDO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."RESULTADOS" MODIFY ("VISITANTE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."RESULTADOS" MODIFY ("LOCAL" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."RESULTADOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."RESULTADOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADOS_DEPOSITOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."ESTADOS_DEPOSITOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."ESTADOS_DEPOSITOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."ESTADOS_DEPOSITOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."ESTADOS_DEPOSITOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table APUESTAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."APUESTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."APUESTAS" MODIFY ("ESTADO_APUESTA_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."APUESTAS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."APUESTAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "USUARIO_1"."APUESTAS" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPOSITOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."DEPOSITOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."DEPOSITOS" MODIFY ("MEDIO_PAGO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."DEPOSITOS" MODIFY ("ESTADO_DEPOSITO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."DEPOSITOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."DEPOSITOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUOTAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."CUOTAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."CUOTAS" MODIFY ("PARTIDO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."CUOTAS" MODIFY ("TIPO_APUESTA_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."CUOTAS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."CUOTAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."PERSONAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."PERSONAS" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."PERSONAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."PERSONAS" MODIFY ("SEGUNDO_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."PERSONAS" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."PERSONAS" MODIFY ("SEGUNDO_APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."PERSONAS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."PERSONAS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."EQUIPOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."EQUIPOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."EQUIPOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RETIROS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."RETIROS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."RETIROS" MODIFY ("BANCO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."RETIROS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."RETIROS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
  ALTER TABLE "USUARIO_1"."RETIROS" MODIFY ("NUMERO_CUENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOVIMIENTOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."MOVIMIENTOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MOVIMIENTOS" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MOVIMIENTOS" MODIFY ("DEPOSITO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MOVIMIENTOS" MODIFY ("RETIRO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MOVIMIENTOS" MODIFY ("SALDO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MOVIMIENTOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."MOVIMIENTOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REQUISITOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."REQUISITOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."REQUISITOS" MODIFY ("RETIRO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."REQUISITOS" MODIFY ("COMPROBANTE_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."REQUISITOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."REQUISITOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SESIONES
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."SESIONES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."SESIONES" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."SESIONES" MODIFY ("FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."SESIONES" MODIFY ("FECHA_FIN" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."SESIONES" MODIFY ("LIMITE_SESION" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."SESIONES" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."SESIONES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BANCOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."BANCOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."BANCOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."BANCOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."BANCOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARTIDOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."PARTIDOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."PARTIDOS" MODIFY ("VISITANTE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."PARTIDOS" MODIFY ("LOCAL" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."PARTIDOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."PARTIDOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BONOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."BONOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."BONOS" MODIFY ("CODIGO_BONO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."BONOS" MODIFY ("FECHA_ACTIVACION" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."BONOS" MODIFY ("FECHA_CADUCIDAD" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."BONOS" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."BONOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."BONOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIMITES_BLOQUEOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."LIMITES_BLOQUEOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."LIMITES_BLOQUEOS" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."LIMITES_BLOQUEOS" MODIFY ("MONTO_APUESTA_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."LIMITES_BLOQUEOS" MODIFY ("MONTO_PERDIDA_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."LIMITES_BLOQUEOS" MODIFY ("LIMITE_DEPOSITO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."LIMITES_BLOQUEOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."LIMITES_BLOQUEOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDIOS_PAGOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."MEDIOS_PAGOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MEDIOS_PAGOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MEDIOS_PAGOS" MODIFY ("VALOR_MINIMO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MEDIOS_PAGOS" MODIFY ("VALOR_MAXIMO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."MEDIOS_PAGOS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
  ALTER TABLE "USUARIO_1"."MEDIOS_PAGOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BET_ITM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PREFERENCIAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."PREFERENCIAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."PREFERENCIAS" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."PREFERENCIAS" MODIFY ("IDIOMA_CORREO" NOT NULL ENABLE);
  ALTER TABLE "USUARIO_1"."PREFERENCIAS" ADD CHECK (ACEPTA_INFORMACION IN ('SI','NO')) ENABLE;
  ALTER TABLE "USUARIO_1"."PREFERENCIAS" ADD CHECK (ACEPTA_BOLETIN IN ('SI','NO')) ENABLE;
  ALTER TABLE "USUARIO_1"."PREFERENCIAS" ADD CHECK (ACEPTA_CORREO_APUESTAS IN ('SI','NO')) ENABLE;
  ALTER TABLE "USUARIO_1"."PREFERENCIAS" ADD CHECK (ACEPTA_NOTIFICACION IN ('SI','NO')) ENABLE;
  ALTER TABLE "USUARIO_1"."PREFERENCIAS" ADD CHECK (ACEPTA_AVISO_APUESTAS IN ('SI','NO')) ENABLE;
  ALTER TABLE "USUARIO_1"."PREFERENCIAS" ADD CHECK (ESTADO_REGISTRO IN ('DISPONIBLE','ELIMINADO')) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APUESTAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."APUESTAS" ADD CONSTRAINT "FK_APUESTAS_ESTADO" FOREIGN KEY ("ESTADO_APUESTA_ID")
	  REFERENCES "USUARIO_1"."ESTADOS_APUESTAS" ("ID") ENABLE;
  ALTER TABLE "USUARIO_1"."APUESTAS" ADD CONSTRAINT "FK_APUESTAS_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "USUARIO_1"."USUARIOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APUESTAS_PARTIDOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."APUESTAS_PARTIDOS" ADD CONSTRAINT "FK_APUESTASPARTIDOS_PARTIDO" FOREIGN KEY ("PARTIDO_ID")
	  REFERENCES "USUARIO_1"."PARTIDOS" ("ID") ENABLE;
  ALTER TABLE "USUARIO_1"."APUESTAS_PARTIDOS" ADD CONSTRAINT "FK_APUESTASPARTIDOS_APUESTA" FOREIGN KEY ("APUESTA_ID")
	  REFERENCES "USUARIO_1"."APUESTAS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BONOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."BONOS" ADD CONSTRAINT "FK_BONOS_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "USUARIO_1"."USUARIOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUOTAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."CUOTAS" ADD CONSTRAINT "FK_CUOTAS_PARTIDO" FOREIGN KEY ("PARTIDO_ID")
	  REFERENCES "USUARIO_1"."PARTIDOS" ("ID") ENABLE;
  ALTER TABLE "USUARIO_1"."CUOTAS" ADD CONSTRAINT "FK_CUOTAS_TIPOAPUESTA" FOREIGN KEY ("TIPO_APUESTA_ID")
	  REFERENCES "USUARIO_1"."TIPOS_APUESTAS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPOSITOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."DEPOSITOS" ADD CONSTRAINT "FK_DEPOSITOS_MEDIOPAGO" FOREIGN KEY ("MEDIO_PAGO_ID")
	  REFERENCES "USUARIO_1"."MEDIOS_PAGOS" ("ID") ENABLE;
  ALTER TABLE "USUARIO_1"."DEPOSITOS" ADD CONSTRAINT "FK_DEPOSITOS_ESTADO" FOREIGN KEY ("ESTADO_DEPOSITO_ID")
	  REFERENCES "USUARIO_1"."ESTADOS_DEPOSITOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIMITES_BLOQUEOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."LIMITES_BLOQUEOS" ADD CONSTRAINT "FK_LIMITESBLOQUEOS_USUARIOS" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "USUARIO_1"."USUARIOS" ("ID") ENABLE;
  ALTER TABLE "USUARIO_1"."LIMITES_BLOQUEOS" ADD CONSTRAINT "FK_LIMITESBLOQUEOS_MONTOAPUESTA" FOREIGN KEY ("MONTO_APUESTA_ID")
	  REFERENCES "USUARIO_1"."MONTOS_APUESTAS" ("ID") ENABLE;
  ALTER TABLE "USUARIO_1"."LIMITES_BLOQUEOS" ADD CONSTRAINT "FK_LIMITESBLOQUEOS_MONTOPERDIDA" FOREIGN KEY ("MONTO_PERDIDA_ID")
	  REFERENCES "USUARIO_1"."MONTOS_PERDIDAS" ("ID") ENABLE;
  ALTER TABLE "USUARIO_1"."LIMITES_BLOQUEOS" ADD CONSTRAINT "FK_LIMITESBLOQUEOS_LIMITEDEPOSITOS" FOREIGN KEY ("LIMITE_DEPOSITO_ID")
	  REFERENCES "USUARIO_1"."LIMITES_DEPOSITOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOVIMIENTOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."MOVIMIENTOS" ADD CONSTRAINT "FK_MOVIMIENTOS_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "USUARIO_1"."USUARIOS" ("ID") ENABLE;
  ALTER TABLE "USUARIO_1"."MOVIMIENTOS" ADD CONSTRAINT "FK_MOVIMIENTOS_DEPOSITO" FOREIGN KEY ("DEPOSITO_ID")
	  REFERENCES "USUARIO_1"."DEPOSITOS" ("ID") ENABLE;
  ALTER TABLE "USUARIO_1"."MOVIMIENTOS" ADD CONSTRAINT "FK_MOVIMIENTOS_RETIRO" FOREIGN KEY ("RETIRO_ID")
	  REFERENCES "USUARIO_1"."RETIROS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MUNICIPIOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."MUNICIPIOS" ADD CONSTRAINT "FK_MUNICIPIOS_DEPARTAMENTO" FOREIGN KEY ("DEPARTAMENTO_ID")
	  REFERENCES "USUARIO_1"."DEPARTAMENTOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTIDOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."PARTIDOS" ADD CONSTRAINT "FK_PARTIDOS_EQUIPOS" FOREIGN KEY ("VISITANTE")
	  REFERENCES "USUARIO_1"."EQUIPOS" ("ID") ENABLE;
  ALTER TABLE "USUARIO_1"."PARTIDOS" ADD CONSTRAINT "FK_PARTIDOS_EQUIPO" FOREIGN KEY ("LOCAL")
	  REFERENCES "USUARIO_1"."EQUIPOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."PERSONAS" ADD CONSTRAINT "FK_PERSONAS_DEPARTAMENTO" FOREIGN KEY ("DEPARTAMENTO_ID")
	  REFERENCES "USUARIO_1"."DEPARTAMENTOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREFERENCIAS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."PREFERENCIAS" ADD CONSTRAINT "FK_PREFERENCIAS_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "USUARIO_1"."USUARIOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUISITOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."REQUISITOS" ADD CONSTRAINT "FK_REQUISITOS_COMPROBANTE" FOREIGN KEY ("COMPROBANTE_ID")
	  REFERENCES "USUARIO_1"."COMPROBANTES" ("ID") ENABLE;
  ALTER TABLE "USUARIO_1"."REQUISITOS" ADD CONSTRAINT "FK_REQUISITOS_RETIRO" FOREIGN KEY ("RETIRO_ID")
	  REFERENCES "USUARIO_1"."RETIROS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESULTADOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."RESULTADOS" ADD CONSTRAINT "FK_RESULTADOS_PARTIDO" FOREIGN KEY ("PARTIDO_ID")
	  REFERENCES "USUARIO_1"."PARTIDOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RETIROS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."RETIROS" ADD CONSTRAINT "FK_RETIROS_BANCO" FOREIGN KEY ("BANCO_ID")
	  REFERENCES "USUARIO_1"."BANCOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SESIONES
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."SESIONES" ADD CONSTRAINT "FK_SESIONES_USUARIO" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "USUARIO_1"."USUARIOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "USUARIO_1"."USUARIOS" ADD CONSTRAINT "FK_USUARIOS_PERSONA" FOREIGN KEY ("PERSONA_ID")
	  REFERENCES "USUARIO_1"."PERSONAS" ("ID") ENABLE;
